# Write your MySQL query statement below
-- SELECT M.TITLE
-- FROM USERS U
-- JOIN MOVIERATING M ON U.USER_ID = M.USER_ID 
-- JOIN MOVIES R ON R.MOVIE_ID =M.MOVIE_ID
-- WHERE M.RATING IN (
--     SELECT AVG(M.RATING) 
--     FROM MOVIERATING M
--     WHERE M.CREATED_AT BETWEEN '2020-02-01' AND '2020-02-29'
-- )
-- ORDER BY U.NAME ASC ;



WITH HIGHESTAVG AS (
    SELECT M.TITLE , AVG(R.RATING) AS AVG_RATING 
    FROM MOVIES M JOIN MOVIERATING R ON M.MOVIE_ID = R.MOVIE_ID 
    WHERE R.CREATED_AT BETWEEN '2020-02-01' AND '2020-02-29'
    GROUP BY M.TITLE 
),
USERNAME AS (
    SELECT U.NAME , COUNT(*) AS RATING_COUNT
    FROM MOVIERATING R JOIN USERS U ON R.USER_ID = U.USER_ID
    GROUP BY U.NAME, U.USER_ID 
),
TOPUSER AS (
    SELECT NAME 
    FROM USERNAME
    ORDER BY RATING_COUNT DESC , NAME ASC
    LIMIT 1
),
TOPMOVIE AS (
    SELECT TITLE 
    FROM HIGHESTAVG 
    ORDER BY AVG_RATING DESC , TITLE ASC 
    LIMIT 1 
)
SELECT NAME AS RESULTS FROM TOPUSER 
UNION ALL 
SELECT TITLE AS RESULTS FROM TOPMOVIE


-- (SELECT Name AS results
-- FROM MovieRating JOIN Users USING(user_id)
-- GROUP BY Name
-- ORDER BY COUNT(*) DESC, Name
-- LIMIT 1)

-- UNION ALL

-- (SELECT title AS results
-- FROM MovieRating JOIN Movies USING(movie_id)
-- WHERE created_at BETWEEN '2020-02-01' AND '2020-02-29'
-- GROUP BY title
-- ORDER BY AVG(rating) DESC, title
-- LIMIT 1);